name: Continuous Integration and Delivery

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_KEY: ${{secrets.REACT_APP_API_KEY}}
      REACT_APP_APP_SERVER_URL: ${{secrets.REACT_APP_APP_SERVER_URL}}
      REACT_APP_AUTH_SERVER_URL: ${{secrets.REACT_APP_AUTH_SERVER_URL}}
      REACT_APP_DISABLED_API_KEY: ${{secrets.REACT_APP_DISABLED_API_KEY}}
      REACT_APP_GENERATE_SOURCEMAP: ${{secrets.REACT_APP_GENERATE_SOURCEMAP}}
      REACT_APP_NODE_OPTIONS: ${{secrets.REACT_APP_NODE_OPTIONS}}
      REACT_APP_NPM_CONFIG_PRODUCTION: ${{secrets.REACT_APP_NPM_CONFIG_PRODUCTION}}
      REACT_APP_PAYMENT_SERVER_URL: ${{secrets.REACT_APP_PAYMENT_SERVER_URL}}
      REACT_APP_POST_SERVER_URL: ${{secrets.REACT_APP_POST_SERVER_URL}}
      REACT_APP_PUBLIC_URL: ${{secrets.REACT_APP_PUBLIC_URL}}
      REACT_APP_USER_SERVER_URL: ${{secrets.REACT_APP_USER_SERVER_URL}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bookbnb-backofficeweb"
          heroku_email: "ftorraca@fi.uba.ar"
