name: Continuous Integration and Delivery

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{secrets.API_KEY}}
      APP_SERVER_URL: ${{secrets.APP_SERVER_URL}}
      AUTH_SERVER_URL: ${{secrets.AUTH_SERVER_URL}}
      DISABLED_API_KEY: ${{secrets.DISABLED_API_KEY}}
      GENERATE_SOURCEMAP: ${{secrets.GENERATE_SOURCEMAP}}
      NODE_OPTIONS: ${{secrets.NODE_OPTIONS}}
      NPM_CONFIG_PRODUCTION: ${{secrets.NPM_CONFIG_PRODUCTION}}
      PAYMENT_SERVER_URL: ${{secrets.PAYMENT_SERVER_URL}}
      POST_SERVER_URL: ${{secrets.POST_SERVER_URL}}
      PUBLIC_URL: ${{secrets.PUBLIC_URL}}
      USER_SERVER_URL: ${{secrets.USER_SERVER_URL}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bookbnb-backofficeweb"
          heroku_email: "ftorraca@fi.uba.ar"
